global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus сам себя мониторит
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Node Exporter (системные метрики)
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']


  - job_name: 'custom_exporter'
    static_configs:
      - targets: ['172.17.0.1:9200']

